/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reportes de una orden o de un equipo
         * @description Hay que indicar uno de los dos filtros, y solo uno: un reporte no se consulta suelto, sino dentro de su orden o del historial de su equipo.
         */
        get: operations["getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api/reports/work-orders/{idOrdenTrabajo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abrir el reporte de un equipo de una orden
         * @description Nace en borrador y vacio. La orden debe haber empezado y el equipo seguir en su alcance; un equipo no tiene dos reportes vivos en la misma orden.
         */
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un reporte por su identificador */
        get: operations["getById"];
        put?: never;
        post?: never;
        /**
         * Retirar un reporte
         * @description No lo borra: lo deja inactivo. Es la unica forma de corregir uno ya cerrado, retirandolo y abriendo otro.
         */
        delete: operations["discard"];
        options?: never;
        head?: never;
        /**
         * Registrar la informacion tecnica (RF-15)
         * @description Un campo ausente deja el valor como estaba y uno en blanco lo borra. Un reporte cerrado ya no se llena.
         */
        patch: operations["fill"];
        trace?: never;
    };
    "/v1/api/reports/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cerrar el reporte
         * @description Exige procedimientos y resultado, y la verificacion completa si el tipo del equipo se verifica. Un equipo que queda fuera de servicio se cierra sin lecturas: no se le puede medir nada. Desde aqui el reporte ya no cambia.
         */
        patch: operations["finish"];
        trace?: never;
    };
    "/v1/api/reports/{id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Registrar la verificacion metrologica
         * @description Sustituye la verificacion anterior entera; las lecturas corregidas quedan retiradas, no borradas. Cada lectura se comprueba contra los puntos y la cantidad de datos que declara el tipo del equipo.
         */
        patch: operations["recordVerification"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GlobalErrorResponse: {
            code?: string;
            details?: string[];
            message?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        RecordVerificationRequest: {
            lecturas: components["schemas"]["VerificationReadingRequest"][];
        };
        ServiceReportErrorResponse: {
            code?: string;
            details?: string[];
            message?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ServiceReportFillRequest: {
            diagnostico?: string;
            /** @description Que reporto el cliente. Nulo deja el valor, blanco lo borra */
            fallaReportada?: string;
            observaciones?: string;
            /** @description Que se hizo. Obligatorio para poder cerrar el reporte */
            procedimientos?: string;
            /**
             * @description Como queda el equipo. Obligatorio para poder cerrar el reporte
             * @enum {string}
             */
            resultado?: "OPERATIVO" | "OPERATIVO_CON_RESTRICCIONES" | "FUERA_DE_SERVICIO";
        };
        ServiceReportOpenRequest: {
            /** Format: uuid */
            idEquipoCliente: string;
        };
        ServiceReportResponse: {
            diagnostico?: string;
            /** @enum {string} */
            estado?: "BORRADOR" | "FINALIZADO";
            estadoActivo?: boolean;
            fallaReportada?: string;
            /**
             * Format: date-time
             * @description Cuando se cerro el reporte. Nulo mientras es borrador
             */
            finalizado?: string;
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            idEquipoCliente?: string;
            /** Format: uuid */
            idOrdenTrabajo?: string;
            lecturas?: components["schemas"]["VerificationReadingResponse"][];
            observaciones?: string;
            procedimientos?: string;
            /** @enum {string} */
            resultado?: "OPERATIVO" | "OPERATIVO_CON_RESTRICCIONES" | "FUERA_DE_SERVICIO";
        };
        VerificationReadingRequest: {
            /**
             * Format: uuid
             * @description Punto en el que se tomo. Nulo solo con patron y equipo variables
             */
            idPuntoVerificacion?: string;
            /**
             * Format: int32
             * @description Cual de las N lecturas de ese punto es
             */
            secuencia?: number;
            /** @description Solo si la lectura no tiene punto; con punto se toma la del punto */
            unidadSinPunto?: string;
            valorEquipo: number;
            valorPatron: number;
        };
        VerificationReadingResponse: {
            /** Format: uuid */
            id?: string;
            /**
             * Format: uuid
             * @description Nulo si la modalidad no declara puntos
             */
            idPuntoVerificacion?: string;
            /** Format: int32 */
            secuencia?: number;
            unidad?: string;
            valorEquipo?: number;
            valorPatron?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAll: {
        parameters: {
            query?: {
                /** @description Los reportes de esta orden de trabajo */
                idOrdenTrabajo?: string;
                /** @description El historial de reportes de este equipo */
                idEquipoCliente?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrdenTrabajo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceReportOpenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
        };
    };
    discard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
        };
    };
    fill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceReportFillRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
        };
    };
    finish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
        };
    };
    recordVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordVerificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServiceReportErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalErrorResponse"];
                };
            };
        };
    };
}
