-- Datos de referencia de ubicaciones: los 249 paises de la ISO 3166-1, los 1103 municipios de
-- Colombia y la capital de cada uno de los demas paises.
--
-- POR QUE ES UNA MIGRACION Y NO UN SCRIPT SUELTO. Sin paises no se puede registrar un fabricante y
-- sin ciudades no se puede abrir una sede: son la primera cosa que una instalacion nueva necesita, y
-- no hay pantalla que las cree -el catalogo de ubicaciones se consulta, no se administra-. Como
-- migracion, Flyway la aplica al arrancar la aplicacion, una sola vez y en cualquier base de datos,
-- que es exactamente lo que se pedia. Un script en docker/postgres/init solo corre al crear el
-- volumen, de modo que no habria tocado la base de datos que ya existe.
--
-- IDEMPOTENTE POR SI ACASO. Lleva ON CONFLICT DO NOTHING sin nombrar la restriccion, de modo que
-- cubre las tres -codigo ISO, nombre de pais y nombre de ciudad por pais- y no pisa lo que alguien
-- hubiera dado de alta a mano antes de esta migracion.
--
-- LOS NOMBRES DE PAIS VAN EN ESPANOL, y no por gusto: son lo que se lee en un desplegable. Salen de
-- la traduccion oficial de iso-codes -Belgium es Belgica, Netherlands es Paises Bajos-, no de una
-- lista escrita a mano, que es como se cuelan los diez paises mal traducidos que nadie revisa.
--
-- LOS 64 NOMBRES REPETIDOS. Colombia tiene cuatro municipios llamados La Union, cuatro Villanueva,
-- cuatro Buenavista y 61 casos mas de nombre compartido entre departamentos. El esquema exige que el
-- nombre sea unico DENTRO de un pais -UQ_ciudad_nombre_por_pais-, asi que los repetidos entran con su
-- departamento entre parentesis: 'La Union (Narino)'. Los demas entran tal cual.
--
-- El comentario de V3__location.sql dice que «el nombre de una ciudad solo es unico dentro de su
-- pais: hay un Cordoba en Espana y otro en Argentina». Es cierto entre paises y FALSO dentro de
-- Colombia, y esta migracion es la primera vez que el proyecto lo contrasta con datos reales. Lo que
-- falta es un nivel de division administrativa -departamento o estado-; queda anotado como deuda.
--
-- UN DEFECTO DE LA FUENTE, corregido al generar: el dataset de municipios trae 'Chibolo' dos veces en
-- Magdalena. Los pares departamento-municipio se deduplican antes de etiquetarlos, de modo que la
-- migracion no depende de que la fuente este limpia.
--
-- FUENTES, por si hay que regenerarlo:
--   paises     iso-codes, /usr/share/iso-codes/json/iso_3166-1.json, con su traduccion al espanol
--   municipios github.com/marcovega/colombia-json (departamentos y municipios de Colombia)
--   capitales  github.com/mledoze/countries (campo capital, emparejado por cca3)
-- Generado el 2026-09-26.

-- Paises: 249
INSERT INTO pais (k_id_pais, k_codigo_iso, n_nombre_pais)
SELECT gen_random_uuid(), datos.iso, datos.nombre
FROM (VALUES
    ('AFG', 'Afganistán'), ('ALB', 'Albania'), ('DEU', 'Alemania'),
    ('DZA', 'Algeria'), ('AND', 'Andorra'), ('AGO', 'Angola'),
    ('AIA', 'Anguila'), ('ATG', 'Antigua y Barbuda'), ('ATA', 'Antártida'),
    ('SAU', 'Arabia Saudí'), ('ARG', 'Argentina'), ('ARM', 'Armenia'),
    ('ABW', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'),
    ('AZE', 'Azerbaiyán'), ('BHS', 'Bahamas'), ('BGD', 'Bangladés'),
    ('BRB', 'Barbados'), ('BHR', 'Baréin'), ('BLZ', 'Belice'),
    ('BEN', 'Benín'), ('BLR', 'Bielorrusia'), ('MMR', 'Birmania'),
    ('BOL', 'Bolivia'), ('BIH', 'Bosnia y Herzegovina'), ('BWA', 'Botsuana'),
    ('BRA', 'Brasil'), ('BRN', 'Brunei Darussalam'), ('BGR', 'Bulgaria'),
    ('BFA', 'Burquina Faso'), ('BDI', 'Burundi'), ('BTN', 'Bután'),
    ('BEL', 'Bélgica'), ('CPV', 'Cabo Verde'), ('KHM', 'Camboya'),
    ('CMR', 'Camerún'), ('CAN', 'Canadá'), ('QAT', 'Catar'),
    ('TCD', 'Chad'), ('CZE', 'Chequia'), ('CHL', 'Chile'),
    ('CHN', 'China'), ('CYP', 'Chipre'), ('COL', 'Colombia'),
    ('COM', 'Comores, Islas'), ('COG', 'Congo'), ('COD', 'Congo, República Democrática del'),
    ('PRK', 'Corea del Norte'), ('KOR', 'Corea del Sur'), ('CRI', 'Costa Rica'),
    ('CIV', 'Costa de Marfíl'), ('HRV', 'Croacia'), ('CUB', 'Cuba'),
    ('CUW', 'Curazao'), ('DNK', 'Dinamarca'), ('DMA', 'Dominica'),
    ('ECU', 'Ecuador'), ('EGY', 'Egipto'), ('SLV', 'El Salvador'),
    ('ARE', 'Emiratos Árabes Unidos'), ('ERI', 'Eritrea'), ('SVK', 'Eslovaquia'),
    ('SVN', 'Eslovenia'), ('ESP', 'España'), ('USA', 'Estados Unidos'),
    ('EST', 'Estonia'), ('SWZ', 'Esuatini'), ('ETH', 'Etiopía'),
    ('RUS', 'Federación Rusa'), ('PHL', 'Filipinas'), ('FIN', 'Finlandia'),
    ('FJI', 'Fiyi'), ('FRA', 'Francia'), ('GAB', 'Gabón'),
    ('GMB', 'Gambia'), ('GEO', 'Georgia'), ('GHA', 'Ghana'),
    ('GIB', 'Gibraltar'), ('GRD', 'Granada'), ('GRC', 'Grecia'),
    ('GRL', 'Groenlandia'), ('GLP', 'Guadalupe'), ('GUM', 'Guam'),
    ('GTM', 'Guatemala'), ('GUF', 'Guayana Francesa'), ('GGY', 'Guernsey'),
    ('GIN', 'Guinea'), ('GNQ', 'Guinea Ecuatorial'), ('GNB', 'Guinea-Bisáu'),
    ('GUY', 'Guyana'), ('HTI', 'Haití'), ('HND', 'Honduras'),
    ('HKG', 'Hong Kong'), ('HUN', 'Hungría'), ('IND', 'India'),
    ('IDN', 'Indonesia'), ('IRQ', 'Irak'), ('IRL', 'Irlanda'),
    ('IRN', 'Irán'), ('BVT', 'Isla Bouvet'), ('HMD', 'Isla Heard e Islas McDonald'),
    ('NFK', 'Isla Norfolk'), ('IMN', 'Isla de Man'), ('CXR', 'Isla de Navidad'),
    ('SXM', 'Isla de San Martín (zona holandesa)'), ('ISL', 'Islandia'), ('BES', 'Islas BES (Caribe Neerlandés)'),
    ('BMU', 'Islas Bermudas'), ('CYM', 'Islas Caimán'), ('CCK', 'Islas Cocos (Keeling)'),
    ('COK', 'Islas Cook'), ('FLK', 'Islas Falkland (Malvinas)'), ('FRO', 'Islas Feroe'),
    ('SGS', 'Islas Georgias del Sur y Sándwich del Sur'), ('MDV', 'Islas Maldivas'), ('MNP', 'Islas Marianas del Norte'),
    ('MHL', 'Islas Marshall'), ('SLB', 'Islas Salomón'), ('TCA', 'Islas Turcas y Caicos'),
    ('UMI', 'Islas Ultramarinas Menores de Estados Unidos'), ('VGB', 'Islas Vírgenes, Británicas'), ('VIR', 'Islas Vírgenes, de EEUU.'),
    ('ALA', 'Islas Äland'), ('ISR', 'Israel'), ('ITA', 'Italia'),
    ('JAM', 'Jamaica'), ('JPN', 'Japón'), ('JEY', 'Jersey'),
    ('JOR', 'Jordania'), ('KAZ', 'Kazajistán'), ('KEN', 'Kenia'),
    ('KGZ', 'Kirguistán'), ('KIR', 'Kiribati'), ('KWT', 'Kuwait'),
    ('LAO', 'Laos'), ('LSO', 'Lesoto'), ('LVA', 'Letonia'),
    ('LBR', 'Liberia'), ('LBY', 'Libia'), ('LIE', 'Liechtenstein'),
    ('LTU', 'Lituania'), ('LUX', 'Luxemburgo'), ('LBN', 'Líbano'),
    ('MAC', 'Macao'), ('MKD', 'Macedonia del Norte'), ('MDG', 'Madagascar'),
    ('MYS', 'Malasia'), ('MWI', 'Malaui'), ('MLT', 'Malta'),
    ('MLI', 'Malí'), ('MAR', 'Marruecos'), ('MTQ', 'Martinica'),
    ('MUS', 'Mauricio'), ('MRT', 'Mauritania'), ('MYT', 'Mayotte'),
    ('FSM', 'Micronesia, Estados Federados de'), ('MDA', 'Moldavia'), ('MNG', 'Mongolia'),
    ('MNE', 'Montenegro'), ('MSR', 'Montserrat'), ('MOZ', 'Mozambique'),
    ('MEX', 'México'), ('MCO', 'Mónaco'), ('NAM', 'Namibia'),
    ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NIC', 'Nicaragua'),
    ('NER', 'Niger'), ('NGA', 'Nigeria'), ('NIU', 'Niue'),
    ('NOR', 'Noruega'), ('NCL', 'Nueva Caledonia'), ('NZL', 'Nueva Zelanda'),
    ('OMN', 'Omán'), ('PAK', 'Pakistán'), ('PLW', 'Palaos'),
    ('PSE', 'Palestina, Estado de'), ('PAN', 'Panamá'), ('PNG', 'Papúa Nueva Guinea'),
    ('PRY', 'Paraguay'), ('NLD', 'Países Bajos'), ('PER', 'Perú'),
    ('PCN', 'Pitcairn'), ('PYF', 'Polinesia Francesa'), ('POL', 'Polonia'),
    ('PRT', 'Portugal'), ('PRI', 'Puerto Rico'), ('GBR', 'Reino Unido'),
    ('CAF', 'República Centroafricana'), ('DOM', 'República Dominicana'), ('REU', 'Reunión'),
    ('RWA', 'Ruanda'), ('ROU', 'Rumanía'), ('ESH', 'Sahara Occidental'),
    ('WSM', 'Samoa'), ('ASM', 'Samoa Estadounidense'), ('BLM', 'San Bartolomé'),
    ('KNA', 'San Cristóbal y Nieves'), ('SMR', 'San Marino'), ('MAF', 'San Martín (zona francesa)'),
    ('SPM', 'San Pedro y Miquelon'), ('VCT', 'San Vicente y las Granadinas'), ('SHN', 'Santa Elena, Ascensión y Tristán de Acuña'),
    ('LCA', 'Santa Lucía'), ('VAT', 'Santa Sede (Ciudad Estado del Vaticano)'), ('STP', 'Santo Tomé y Príncipe'),
    ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'),
    ('SLE', 'Sierra Leona'), ('SGP', 'Singapur'), ('SYR', 'Siria'),
    ('SOM', 'Somalia'), ('LKA', 'Sri Lanka'), ('ZAF', 'Sudáfrica'),
    ('SDN', 'Sudán'), ('SSD', 'Sudán del Sur'), ('SWE', 'Suecia'),
    ('CHE', 'Suiza'), ('SUR', 'Surinám'), ('SJM', 'Svalbard y Jan Mayen'),
    ('THA', 'Tailandia'), ('TWN', 'Taiwán'), ('TZA', 'Tanzania'),
    ('TJK', 'Tayikistán'), ('IOT', 'Territorio Británico del Océano Índico'), ('ATF', 'Territorios Franceses del Sur'),
    ('TLS', 'Timor Oriental'), ('TGO', 'Togo'), ('TKL', 'Tokelau'),
    ('TON', 'Tonga'), ('TTO', 'Trinidad y Tobago'), ('TUN', 'Tunez'),
    ('TKM', 'Turkmenistán'), ('TUR', 'Turquía'), ('TUV', 'Tuvalu'),
    ('UKR', 'Ucrania'), ('UGA', 'Uganda'), ('URY', 'Uruguay'),
    ('UZB', 'Uzbekistán'), ('VUT', 'Vanuatu'), ('VEN', 'Venezuela'),
    ('VNM', 'Vietnam'), ('WLF', 'Wallis y Futuna'), ('YEM', 'Yemen'),
    ('DJI', 'Yibuti'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabue')
) AS datos(iso, nombre)
ON CONFLICT DO NOTHING;

-- Municipios de Colombia: 1103
INSERT INTO ciudad (k_id_ciudad, n_nombre_ciudad, k_id_pais)
SELECT gen_random_uuid(), datos.ciudad, pais.k_id_pais
FROM (VALUES
    ('Abejorral'), ('Abriaquí'), ('Acacías'), ('Acandí'),
    ('Acevedo'), ('Achí'), ('Agrado'), ('Agua de Dios'),
    ('Aguachica'), ('Aguada'), ('Aguadas'), ('Aguazul'),
    ('Agustín Codazzi'), ('Aipe'), ('Albania (Caquetá)'), ('Albania (La Guajira)'),
    ('Albania (Santander)'), ('Albán'), ('Alcalá'), ('Aldana'),
    ('Alejandría'), ('Algarrobo'), ('Algeciras'), ('Almaguer'),
    ('Almeida'), ('Alpujarra'), ('Altamira'), ('Alto Baudó'),
    ('Altos del Rosario'), ('Alvarado'), ('Amagá'), ('Amalfi'),
    ('Ambalema'), ('Anapoima'), ('Ancuyá'), ('Andalucía'),
    ('Andes'), ('Angelópolis'), ('Angostura'), ('Anolaima'),
    ('Anorí'), ('Anserma'), ('Ansermanuevo'), ('Anzoátegui'),
    ('Anzá'), ('Apartadó'), ('Apulo'), ('Apía'),
    ('Aquitania'), ('Aracataca'), ('Aranzazu'), ('Aratoca'),
    ('Arauca'), ('Arauquita'), ('Arbeláez'), ('Arboleda'),
    ('Arboledas'), ('Arboletes'), ('Arcabuco'), ('Arenal'),
    ('Argelia (Antioquia)'), ('Argelia (Cauca)'), ('Argelia (Valle del Cauca)'), ('Ariguaní'),
    ('Arjona'), ('Armenia (Antioquia)'), ('Armenia (Quindío)'), ('Armero'),
    ('Arroyohondo'), ('Astrea'), ('Ataco'), ('Ayapel'),
    ('Bagadó'), ('Bahía Solano'), ('Bajo Baudó'), ('Balboa (Cauca)'),
    ('Balboa (Risaralda)'), ('Baranoa'), ('Baraya'), ('Barbacoas'),
    ('Barbosa (Antioquia)'), ('Barbosa (Santander)'), ('Barichara'), ('Barranca de Upía'),
    ('Barrancabermeja'), ('Barrancas'), ('Barranco de Loba'), ('Barranquilla'),
    ('Becerril'), ('Belalcázar'), ('Bello'), ('Belmira'),
    ('Beltrán'), ('Belén (Boyacá)'), ('Belén (Nariño)'), ('Belén de Umbría'),
    ('Belén de los Andaquíes'), ('Berbeo'), ('Betania'), ('Betulia (Antioquia)'),
    ('Betulia (Santander)'), ('Betéitiva'), ('Bituima'), ('Boavita'),
    ('Bochalema'), ('Bogotá'), ('Bojacá'), ('Bojayá'),
    ('Bolívar (Cauca)'), ('Bolívar (Santander)'), ('Bolívar (Valle del Cauca)'), ('Bosconia'),
    ('Boyacá'), ('Brazuelo de Papayal'), ('Briceño (Antioquia)'), ('Briceño (Boyacá)'),
    ('Bucaramanga'), ('Bucarasica'), ('Buenaventura'), ('Buenavista (Boyacá)'),
    ('Buenavista (Córdoba)'), ('Buenavista (Quindío)'), ('Buenavista (Sucre)'), ('Buenos Aires'),
    ('Buesaco'), ('Buga'), ('Bugalagrande'), ('Buriticá'),
    ('Busbanzá'), ('Cabrera (Cundinamarca)'), ('Cabrera (Santander)'), ('Cabuyaro'),
    ('Cachipay'), ('Caicedo'), ('Caicedonia'), ('Caimito'),
    ('Cajamarca'), ('Cajibío'), ('Cajicá'), ('Calamar (Bolívar)'),
    ('Calamar (Guaviare)'), ('Calarcá'), ('Caldas (Antioquia)'), ('Caldas (Boyacá)'),
    ('Caldono'), ('Cali'), ('California'), ('Calima'),
    ('Caloto'), ('Campamento'), ('Campo de la Cruz'), ('Campoalegre'),
    ('Campohermoso'), ('Canalete'), ('Candelaria (Atlántico)'), ('Candelaria (Valle del Cauca)'),
    ('Cantagallo'), ('Cantón de San Pablo'), ('Caparrapí'), ('Capitanejo'),
    ('Caracolí'), ('Caramanta'), ('Carcasí'), ('Carepa'),
    ('Carmen de Apicalá'), ('Carmen de Carupa'), ('Carolina del Príncipe'), ('Cartagena de Indias'),
    ('Cartagena del Chairá'), ('Cartago'), ('Carurú'), ('Casabianca'),
    ('Castilla la Nueva'), ('Caucasia'), ('Cañasgordas'), ('Cepitá'),
    ('Cereté'), ('Cerinza'), ('Cerrito'), ('Cerro de San Antonio'),
    ('Chachagüí'), ('Chaguaní'), ('Chalán'), ('Chaparral'),
    ('Charalá'), ('Charta'), ('Chibolo'), ('Chigorodó'),
    ('Chima'), ('Chimichagua'), ('Chimá'), ('Chinavita'),
    ('Chinchiná'), ('Chinácota'), ('Chinú'), ('Chipaque'),
    ('Chipatá'), ('Chiquinquirá'), ('Chiriguaná'), ('Chiscas'),
    ('Chita'), ('Chitagá'), ('Chitaraque'), ('Chivatá'),
    ('Chivor'), ('Choachí'), ('Chocontá'), ('Chámeza'),
    ('Chía'), ('Chíquiza'), ('Cicuco'), ('Cimitarra'),
    ('Circasia'), ('Cisneros'), ('Ciudad Bolívar'), ('Ciénaga'),
    ('Ciénaga de Oro'), ('Ciénega'), ('Clemencia'), ('Cocorná'),
    ('Coello'), ('Cogua'), ('Colombia'), ('Colosó'),
    ('Colón (Nariño)'), ('Colón (Putumayo)'), ('Concepción (Antioquia)'), ('Concepción (Santander)'),
    ('Concordia (Antioquia)'), ('Concordia (Magdalena)'), ('Condoto'), ('Confines'),
    ('Consacá'), ('Contadero'), ('Contratación'), ('Convención'),
    ('Copacabana'), ('Coper'), ('Corinto'), ('Coromoro'),
    ('Corozal'), ('Corrales'), ('Cota'), ('Cotorra'),
    ('Covarachía'), ('Coveñas'), ('Coyaima'), ('Cravo Norte'),
    ('Cuaspud'), ('Cubarral'), ('Cubará'), ('Cucaita'),
    ('Cucunubá'), ('Cucutilla'), ('Cumaral'), ('Cumaribo'),
    ('Cumbal'), ('Cumbitara'), ('Cunday'), ('Curillo'),
    ('Curití'), ('Curumaní'), ('Cuítiva'), ('Cáceres'),
    ('Cáchira'), ('Cácota'), ('Cáqueza'), ('Cértegui'),
    ('Cómbita'), ('Córdoba (Bolívar)'), ('Córdoba (Nariño)'), ('Córdoba (Quindío)'),
    ('Cúcuta'), ('Dabeiba'), ('Dagua'), ('Dibulla'),
    ('Distracción'), ('Dolores'), ('Donmatías'), ('Dosquebradas'),
    ('Duitama'), ('Duranía'), ('Ebéjico'), ('El Atrato'),
    ('El Bagre'), ('El Banco'), ('El Cairo'), ('El Calvario'),
    ('El Carmen'), ('El Carmen de Atrato'), ('El Carmen de Bolívar'), ('El Carmen de Chucurí'),
    ('El Carmen de Viboral'), ('El Carmen del Darién'), ('El Castillo'), ('El Cerrito'),
    ('El Charco'), ('El Cocuy'), ('El Colegio'), ('El Copey'),
    ('El Doncello'), ('El Dorado'), ('El Dovio'), ('El Espinal'),
    ('El Espino'), ('El Guacamayo'), ('El Guamo'), ('El Molino'),
    ('El Paso'), ('El Paujil'), ('El Peñol (Antioquia)'), ('El Peñol (Nariño)'),
    ('El Peñón (Bolívar)'), ('El Peñón (Cundinamarca)'), ('El Peñón (Santander)'), ('El Pital'),
    ('El Piñón'), ('El Playón'), ('El Retiro'), ('El Retorno'),
    ('El Retén'), ('El Roble'), ('El Rosal'), ('El Rosario'),
    ('El Santuario'), ('El Socorro'), ('El Tablón'), ('El Tambo (Cauca)'),
    ('El Tambo (Nariño)'), ('El Tarra'), ('El Zulia'), ('El Águila'),
    ('Elías'), ('Encino'), ('Enciso'), ('Entrerríos'),
    ('Envigado'), ('Facatativá'), ('Falán'), ('Filadelfia'),
    ('Filandia'), ('Firavitoba'), ('Flandes'), ('Florencia (Caquetá)'),
    ('Florencia (Cauca)'), ('Floresta'), ('Florida'), ('Floridablanca'),
    ('Florián'), ('Fonseca'), ('Fortul'), ('Fosca'),
    ('Francisco Pizarro'), ('Fredonia'), ('Fresno'), ('Frontino'),
    ('Fuente de Oro'), ('Fundación'), ('Funes'), ('Funza'),
    ('Fusagasugá'), ('Fómeque'), ('Fúquene'), ('Gachalá'),
    ('Gachancipá'), ('Gachantivá'), ('Gachetá'), ('Galapa'),
    ('Galeras'), ('Galán'), ('Gama'), ('Gamarra'),
    ('Garagoa'), ('Garzón'), ('Gigante'), ('Ginebra'),
    ('Giraldo'), ('Girardot'), ('Girardota'), ('Girón'),
    ('González'), ('Gramalote'), ('Granada (Antioquia)'), ('Granada (Cundinamarca)'),
    ('Granada (Meta)'), ('Guaca'), ('Guacamayas'), ('Guacarí'),
    ('Guachené'), ('Guachetá'), ('Guachucal'), ('Guadalupe (Antioquia)'),
    ('Guadalupe (Huila)'), ('Guadalupe (Santander)'), ('Guaduas'), ('Guaitarilla'),
    ('Gualmatán'), ('Guamal (Magdalena)'), ('Guamal (Meta)'), ('Guamo'),
    ('Guapotá'), ('Guapí'), ('Guaranda'), ('Guarne'),
    ('Guasca'), ('Guatapé'), ('Guataquí'), ('Guatavita'),
    ('Guateque'), ('Guavatá'), ('Guayabal de Síquima'), ('Guayabetal'),
    ('Guayatá'), ('Gutiérrez'), ('Guática'), ('Gámbita'),
    ('Gámeza'), ('Génova'), ('Gómez Plata'), ('Güepsa'),
    ('Güicán'), ('Hacarí'), ('Hatillo de Loba'), ('Hato'),
    ('Hato Corozal'), ('Hatonuevo'), ('Heliconia'), ('Herrán'),
    ('Herveo'), ('Hispania'), ('Hobo'), ('Honda'),
    ('Ibagué'), ('Icononzo'), ('Iles'), ('Imués'),
    ('Inzá'), ('Inírida'), ('Ipiales'), ('Isnos'),
    ('Istmina'), ('Itagüí'), ('Ituango'), ('Iza'),
    ('Jambaló'), ('Jamundí'), ('Jardín'), ('Jenesano'),
    ('Jericó (Antioquia)'), ('Jericó (Boyacá)'), ('Jerusalén'), ('Jesús María'),
    ('Jordán'), ('Juan de Acosta'), ('Junín'), ('Juradó'),
    ('La Apartada'), ('La Argentina'), ('La Belleza'), ('La Calera'),
    ('La Capilla'), ('La Ceja'), ('La Celia'), ('La Cruz'),
    ('La Cumbre'), ('La Dorada'), ('La Esperanza'), ('La Estrella'),
    ('La Florida'), ('La Gloria (Cesar)'), ('La Jagua de Ibirico'), ('La Jagua del Pilar'),
    ('La Llanada'), ('La Macarena'), ('La Merced'), ('La Mesa'),
    ('La Montañita'), ('La Palma'), ('La Paz (Cesar)'), ('La Paz (Santander)'),
    ('La Peña'), ('La Pintada'), ('La Plata'), ('La Playa de Belén'),
    ('La Primavera'), ('La Salina'), ('La Sierra'), ('La Tebaida'),
    ('La Tola'), ('La Unión (Antioquia)'), ('La Unión (Nariño)'), ('La Unión (Sucre)'),
    ('La Unión (Valle del Cauca)'), ('La Uribe'), ('La Uvita'), ('La Vega (Cauca)'),
    ('La Vega (Cundinamarca)'), ('La Victoria (Boyacá)'), ('La Victoria (Valle del Cauca)'), ('La Virginia'),
    ('Labateca'), ('Labranzagrande'), ('Landázuri'), ('Lebrija'),
    ('Leiva'), ('Lejanías'), ('Lenguazaque'), ('Leticia'),
    ('Liborina'), ('Linares'), ('Litoral de San Juan'), ('Lloró'),
    ('Lorica'), ('Los Andes'), ('Los Córdobas'), ('Los Palmitos'),
    ('Los Patios'), ('Los Santos'), ('Lourdes'), ('Luruaco'),
    ('Lérida'), ('Líbano'), ('López de Micay'), ('Macanal'),
    ('Macaravita'), ('Maceo'), ('Machetá'), ('Madrid'),
    ('Magangué'), ('Magüí Payán'), ('Mahates'), ('Maicao'),
    ('Majagual'), ('Malambo'), ('Mallama'), ('Manatí'),
    ('Manaure'), ('Manaure Balcón del Cesar'), ('Manizales'), ('Manta'),
    ('Manzanares'), ('Maní'), ('Mapiripán'), ('Margarita'),
    ('Marinilla'), ('Maripí'), ('Mariquita'), ('Marmato'),
    ('Marquetalia'), ('Marsella'), ('Marulanda'), ('María la Baja'),
    ('Matanza'), ('Medellín'), ('Medina'), ('Medio Atrato'),
    ('Medio Baudó'), ('Medio San Juan'), ('Melgar'), ('Mercaderes'),
    ('Mesetas'), ('Milán'), ('Miraflores (Boyacá)'), ('Miraflores (Guaviare)'),
    ('Miranda'), ('Mistrató'), ('Mitú'), ('Mocoa'),
    ('Mogotes'), ('Molagavita'), ('Momil'), ('Mompós'),
    ('Mongua'), ('Monguí'), ('Moniquirá'), ('Montebello'),
    ('Montecristo'), ('Montelíbano'), ('Montenegro'), ('Monterrey'),
    ('Montería'), ('Morales (Bolívar)'), ('Morales (Cauca)'), ('Morelia'),
    ('Morroa'), ('Mosquera (Cundinamarca)'), ('Mosquera (Nariño)'), ('Motavita'),
    ('Moñitos'), ('Murillo'), ('Murindó'), ('Mutatá'),
    ('Mutiscua'), ('Muzo'), ('Málaga'), ('Nariño (Antioquia)'),
    ('Nariño (Cundinamarca)'), ('Nariño (Nariño)'), ('Natagaima'), ('Nechí'),
    ('Necoclí'), ('Neira'), ('Neiva'), ('Nemocón'),
    ('Nilo'), ('Nimaima'), ('Nobsa'), ('Nocaima'),
    ('Norcasia'), ('Norosí'), ('Nueva Granada'), ('Nuevo Colón'),
    ('Nunchía'), ('Nuquí'), ('Nátaga'), ('Nóvita'),
    ('Obando'), ('Ocamonte'), ('Ocaña'), ('Oiba'),
    ('Oicatá'), ('Olaya'), ('Olaya Herrera'), ('Onzaga'),
    ('Oporapa'), ('Orito'), ('Orocué'), ('Ortega'),
    ('Ospina'), ('Otanche'), ('Ovejas'), ('Pachavita'),
    ('Pacho'), ('Padilla'), ('Paicol'), ('Pailitas'),
    ('Paime'), ('Paipa'), ('Pajarito'), ('Palermo'),
    ('Palestina (Caldas)'), ('Palestina (Huila)'), ('Palmar'), ('Palmar de Varela'),
    ('Palmas del Socorro'), ('Palmira'), ('Palocabildo'), ('Pamplona'),
    ('Pamplonita'), ('Pandi'), ('Panqueba'), ('Paratebueno'),
    ('Pasca'), ('Pasto'), ('Patía'), ('Pauna'),
    ('Paya'), ('Paz de Ariporo'), ('Paz del Río'), ('Pedraza'),
    ('Pelaya'), ('Pensilvania'), ('Peque'), ('Pereira'),
    ('Pesca'), ('Piamonte'), ('Piedecuesta'), ('Piedras'),
    ('Piendamó'), ('Pijao'), ('Pijiño del Carmen'), ('Pinchote'),
    ('Pinillos'), ('Piojó'), ('Pisba'), ('Pitalito'),
    ('Pivijay'), ('Planadas'), ('Planeta Rica'), ('Plato'),
    ('Policarpa'), ('Polonuevo'), ('Ponedera'), ('Popayán'),
    ('Pore'), ('Potosí'), ('Pradera'), ('Prado'),
    ('Providencia'), ('Providencia y Santa Catalina Islas'), ('Pueblo Bello'), ('Pueblo Nuevo'),
    ('Pueblo Rico'), ('Pueblo Viejo'), ('Pueblorrico'), ('Puente Nacional'),
    ('Puerres'), ('Puerto Asís'), ('Puerto Berrío'), ('Puerto Boyacá'),
    ('Puerto Caicedo'), ('Puerto Carreño'), ('Puerto Colombia'), ('Puerto Concordia'),
    ('Puerto Escondido'), ('Puerto Gaitán'), ('Puerto Guzmán'), ('Puerto Leguízamo'),
    ('Puerto Libertador'), ('Puerto Lleras'), ('Puerto López'), ('Puerto Nare'),
    ('Puerto Nariño'), ('Puerto Parra'), ('Puerto Rico (Caquetá)'), ('Puerto Rico (Meta)'),
    ('Puerto Rondón'), ('Puerto Salgar'), ('Puerto Santander'), ('Puerto Tejada'),
    ('Puerto Triunfo'), ('Puerto Wilches'), ('Pulí'), ('Pupiales'),
    ('Puracé'), ('Purificación'), ('Purísima'), ('Pácora'),
    ('Páez (Boyacá)'), ('Páez (Cauca)'), ('Páramo'), ('Quebradanegra'),
    ('Quetame'), ('Quibdó'), ('Quimbaya'), ('Quinchía'),
    ('Quipile'), ('Quípama'), ('Ragonvalia'), ('Ramiriquí'),
    ('Recetor'), ('Regidor'), ('Remedios'), ('Remolino'),
    ('Repelón'), ('Restrepo (Meta)'), ('Restrepo (Valle del Cauca)'), ('Ricaurte (Cundinamarca)'),
    ('Ricaurte (Nariño)'), ('Rioblanco'), ('Riofrío'), ('Riohacha'),
    ('Rionegro (Antioquia)'), ('Rionegro (Santander)'), ('Riosucio (Caldas)'), ('Riosucio (Chocó)'),
    ('Risaralda'), ('Rivera'), ('Roberto Payán'), ('Roldanillo'),
    ('Roncesvalles'), ('Rondón'), ('Rosas'), ('Rovira'),
    ('Ráquira'), ('Río Iró'), ('Río Quito'), ('Río Viejo'),
    ('Río de Oro'), ('Sabana de Torres'), ('Sabanagrande'), ('Sabanalarga (Antioquia)'),
    ('Sabanalarga (Atlántico)'), ('Sabanalarga (Casanare)'), ('Sabanas de San Ángel'), ('Sabaneta'),
    ('Saboyá'), ('Sahagún'), ('Saladoblanco'), ('Salamina (Caldas)'),
    ('Salamina (Magdalena)'), ('Salazar de Las Palmas'), ('Saldaña'), ('Salento'),
    ('Salgar'), ('Samacá'), ('Samaniego'), ('Samaná'),
    ('Sampués'), ('San Agustín'), ('San Alberto'), ('San Andrés (San Andrés y Providencia)'),
    ('San Andrés (Santander)'), ('San Andrés de Cuerquia'), ('San Andrés de Sotavento'), ('San Antero'),
    ('San Antonio'), ('San Antonio de Palmito'), ('San Antonio del Tequendama'), ('San Benito'),
    ('San Benito Abad'), ('San Bernardo (Cundinamarca)'), ('San Bernardo (Nariño)'), ('San Bernardo del Viento'),
    ('San Calixto'), ('San Carlos (Antioquia)'), ('San Carlos (Córdoba)'), ('San Carlos de Guaroa'),
    ('San Cayetano (Cundinamarca)'), ('San Cayetano (Norte de Santander)'), ('San Cristóbal'), ('San Diego'),
    ('San Eduardo'), ('San Estanislao'), ('San Fernando'), ('San Francisco (Antioquia)'),
    ('San Francisco (Cundinamarca)'), ('San Francisco (Putumayo)'), ('San Gil'), ('San Jacinto'),
    ('San Jacinto del Cauca'), ('San Jerónimo'), ('San Joaquín'), ('San José'),
    ('San José de Albán'), ('San José de Miranda'), ('San José de Pare'), ('San José de Uré'),
    ('San José de la Montaña'), ('San José del Fragua'), ('San José del Guaviare'), ('San José del Palmar'),
    ('San Juan Nepomuceno'), ('San Juan de Arama'), ('San Juan de Betulia'), ('San Juan de Rioseco'),
    ('San Juan de Urabá'), ('San Juan del Cesar'), ('San Juanito'), ('San Lorenzo'),
    ('San Luis (Antioquia)'), ('San Luis (Tolima)'), ('San Luis de Gaceno'), ('San Luis de Palenque'),
    ('San Marcos'), ('San Martín (Cesar)'), ('San Martín (Meta)'), ('San Martín de Loba'),
    ('San Mateo'), ('San Miguel (Putumayo)'), ('San Miguel (Santander)'), ('San Miguel de Sema'),
    ('San Onofre'), ('San Pablo (Bolívar)'), ('San Pablo (Nariño)'), ('San Pablo de Borbur'),
    ('San Pedro (Sucre)'), ('San Pedro (Valle del Cauca)'), ('San Pedro de Cartago'), ('San Pedro de Urabá'),
    ('San Pedro de los Milagros'), ('San Pelayo'), ('San Rafael'), ('San Roque'),
    ('San Sebastián'), ('San Sebastián de Buenavista'), ('San Vicente'), ('San Vicente de Chucurí'),
    ('San Vicente del Caguán'), ('San Zenón'), ('Sandoná'), ('Santa Ana'),
    ('Santa Bárbara (Antioquia)'), ('Santa Bárbara (Nariño)'), ('Santa Bárbara (Santander)'), ('Santa Bárbara de Pinto'),
    ('Santa Catalina'), ('Santa Fe de Antioquia'), ('Santa Helena del Opón'), ('Santa Isabel'),
    ('Santa Lucía'), ('Santa Marta'), ('Santa María (Boyacá)'), ('Santa María (Huila)'),
    ('Santa Rosa (Bolívar)'), ('Santa Rosa (Cauca)'), ('Santa Rosa de Cabal'), ('Santa Rosa de Osos'),
    ('Santa Rosa de Viterbo'), ('Santa Rosa del Sur'), ('Santa Rosalía'), ('Santa Sofía'),
    ('Santacruz'), ('Santana'), ('Santander de Quilichao'), ('Santiago (Norte de Santander)'),
    ('Santiago (Putumayo)'), ('Santo Domingo'), ('Santo Domingo de Silos'), ('Santo Tomás'),
    ('Santuario'), ('Sapuyes'), ('Saravena'), ('Sardinata'),
    ('Sasaima'), ('Sativanorte'), ('Sativasur'), ('Segovia'),
    ('Sesquilé'), ('Sevilla'), ('Siachoque'), ('Sibaté'),
    ('Sibundoy'), ('Silvania'), ('Silvia'), ('Simacota'),
    ('Simijaca'), ('Simití'), ('Sincelejo'), ('Sincé'),
    ('Sipí'), ('Sitionuevo'), ('Soacha'), ('Soatá'),
    ('Socha'), ('Socotá'), ('Sogamoso'), ('Solano'),
    ('Soledad'), ('Solita'), ('Somondoco'), ('Sonsón'),
    ('Sopetrán'), ('Soplaviento'), ('Sopó'), ('Sora'),
    ('Soracá'), ('Sotaquirá'), ('Sotará'), ('Suaita'),
    ('Suaza'), ('Subachoque'), ('Sucre (Cauca)'), ('Sucre (Santander)'),
    ('Sucre (Sucre)'), ('Suesca'), ('Supatá'), ('Supía'),
    ('Suratá'), ('Susa'), ('Susacón'), ('Sutamarchán'),
    ('Sutatausa'), ('Sutatenza'), ('Suán'), ('Suárez (Cauca)'),
    ('Suárez (Tolima)'), ('Sácama'), ('Sáchica'), ('Tabio'),
    ('Tadó'), ('Talaigua Nuevo'), ('Tamalameque'), ('Tame'),
    ('Taminango'), ('Tangua'), ('Taraira'), ('Tarazá'),
    ('Tarqui'), ('Tarso'), ('Tasco'), ('Tauramena'),
    ('Tausa'), ('Tello'), ('Tena'), ('Tenerife'),
    ('Tenjo'), ('Tenza'), ('Teorama'), ('Teruel'),
    ('Tesalia'), ('Tibacuy'), ('Tibaná'), ('Tibasosa'),
    ('Tibirita'), ('Tibú'), ('Tierralta'), ('Timaná'),
    ('Timbiquí'), ('Timbío'), ('Tinjacá'), ('Tipacoque'),
    ('Tiquisio'), ('Titiribí'), ('Toca'), ('Tocaima'),
    ('Tocancipá'), ('Togüí'), ('Toledo (Antioquia)'), ('Toledo (Norte de Santander)'),
    ('Tolú'), ('Tolú Viejo'), ('Tona'), ('Topaipí'),
    ('Toribío'), ('Toro'), ('Tota'), ('Totoró'),
    ('Trinidad'), ('Trujillo'), ('Tubará'), ('Tuchín'),
    ('Tuluá'), ('Tumaco'), ('Tunja'), ('Tununguá'),
    ('Turbaco'), ('Turbaná'), ('Turbo'), ('Turmequé'),
    ('Tuta'), ('Tutazá'), ('Támara'), ('Támesis'),
    ('Tópaga'), ('Túquerres'), ('Ubalá'), ('Ubaque'),
    ('Ubaté'), ('Ulloa'), ('Une'), ('Unguía'),
    ('Unión Panamericana'), ('Uramita'), ('Uribia'), ('Urrao'),
    ('Urumita'), ('Usiacurí'), ('Valdivia'), ('Valencia'),
    ('Valle de San José'), ('Valle de San Juan'), ('Valle del Guamuez'), ('Valledupar'),
    ('Valparaíso (Antioquia)'), ('Valparaíso (Caquetá)'), ('Vegachí'), ('Venadillo'),
    ('Venecia (Antioquia)'), ('Venecia (Cundinamarca)'), ('Ventaquemada'), ('Vergara'),
    ('Versalles'), ('Vetas'), ('Vianí'), ('Victoria'),
    ('Vigía del Fuerte'), ('Vijes'), ('Villa Caro'), ('Villa Rica'),
    ('Villa de Leyva'), ('Villa del Rosario'), ('Villagarzón'), ('Villagómez'),
    ('Villahermosa'), ('Villamaría'), ('Villanueva (Bolívar)'), ('Villanueva (Casanare)'),
    ('Villanueva (La Guajira)'), ('Villanueva (Santander)'), ('Villapinzón'), ('Villarrica'),
    ('Villavicencio'), ('Villavieja'), ('Villeta'), ('Viotá'),
    ('Viracachá'), ('Vista Hermosa'), ('Viterbo'), ('Vélez'),
    ('Yacopí'), ('Yacuanquer'), ('Yaguará'), ('Yalí'),
    ('Yarumal'), ('Yolombó'), ('Yondó'), ('Yopal'),
    ('Yotoco'), ('Yumbo'), ('Zambrano'), ('Zapatoca'),
    ('Zapayán'), ('Zaragoza'), ('Zarzal'), ('Zetaquira'),
    ('Zipacón'), ('Zipaquirá'), ('Zona Bananera'), ('Ábrego'),
    ('Íquira'), ('Úmbita'), ('Útica')
) AS datos(ciudad)
JOIN pais ON pais.k_codigo_iso = 'COL'
ON CONFLICT DO NOTHING;

-- Capital de cada uno de los demas paises: 247
--
-- Solo la capital, y no todas sus ciudades: una ciudad aqui sirve para ubicar la sede de un cliente, y
-- los clientes de esta empresa estan en Colombia. Meter cien mil ciudades del mundo entero llenaria un
-- desplegable que nadie usa. Si algun dia hay un cliente fuera, se anade la ciudad que haga falta.
INSERT INTO ciudad (k_id_ciudad, n_nombre_ciudad, k_id_pais)
SELECT gen_random_uuid(), datos.ciudad, pais.k_id_pais
FROM (VALUES
    ('ABW', 'Oranjestad'), ('AFG', 'Kabul'), ('AGO', 'Luanda'),
    ('AIA', 'The Valley'), ('ALA', 'Mariehamn'), ('ALB', 'Tirana'),
    ('AND', 'Andorra la Vella'), ('ARE', 'Abu Dhabi'), ('ARG', 'Buenos Aires'),
    ('ARM', 'Yerevan'), ('ASM', 'Pago Pago'), ('ATF', 'Port-aux-Français'),
    ('ATG', 'Saint John''s'), ('AUS', 'Canberra'), ('AUT', 'Vienna'),
    ('AZE', 'Baku'), ('BDI', 'Gitega'), ('BEL', 'Brussels'),
    ('BEN', 'Porto-Novo'), ('BES', 'Kralendijk'), ('BES', 'Oranjestad'),
    ('BES', 'The Bottom'), ('BFA', 'Ouagadougou'), ('BGD', 'Dhaka'),
    ('BGR', 'Sofia'), ('BHR', 'Manama'), ('BHS', 'Nassau'),
    ('BIH', 'Sarajevo'), ('BLM', 'Gustavia'), ('BLR', 'Minsk'),
    ('BLZ', 'Belmopan'), ('BMU', 'Hamilton'), ('BOL', 'Sucre'),
    ('BRA', 'Brasília'), ('BRB', 'Bridgetown'), ('BRN', 'Bandar Seri Begawan'),
    ('BTN', 'Thimphu'), ('BWA', 'Gaborone'), ('CAF', 'Bangui'),
    ('CAN', 'Ottawa'), ('CCK', 'West Island'), ('CHE', 'Bern'),
    ('CHL', 'Santiago'), ('CHN', 'Beijing'), ('CIV', 'Yamoussoukro'),
    ('CMR', 'Yaoundé'), ('COD', 'Kinshasa'), ('COG', 'Brazzaville'),
    ('COK', 'Avarua'), ('COM', 'Moroni'), ('CPV', 'Praia'),
    ('CRI', 'San José'), ('CUB', 'Havana'), ('CUW', 'Willemstad'),
    ('CXR', 'Flying Fish Cove'), ('CYM', 'George Town'), ('CYP', 'Nicosia'),
    ('CZE', 'Prague'), ('DEU', 'Berlin'), ('DJI', 'Djibouti'),
    ('DMA', 'Roseau'), ('DNK', 'Copenhagen'), ('DOM', 'Santo Domingo'),
    ('DZA', 'Algiers'), ('ECU', 'Quito'), ('EGY', 'Cairo'),
    ('ERI', 'Asmara'), ('ESH', 'El Aaiún'), ('ESP', 'Madrid'),
    ('EST', 'Tallinn'), ('ETH', 'Addis Ababa'), ('FIN', 'Helsinki'),
    ('FJI', 'Suva'), ('FLK', 'Stanley'), ('FRA', 'Paris'),
    ('FRO', 'Tórshavn'), ('FSM', 'Palikir'), ('GAB', 'Libreville'),
    ('GBR', 'London'), ('GEO', 'Tbilisi'), ('GGY', 'St. Peter Port'),
    ('GHA', 'Accra'), ('GIB', 'Gibraltar'), ('GIN', 'Conakry'),
    ('GLP', 'Basse-Terre'), ('GMB', 'Banjul'), ('GNB', 'Bissau'),
    ('GNQ', 'Malabo'), ('GRC', 'Athens'), ('GRD', 'St. George''s'),
    ('GRL', 'Nuuk'), ('GTM', 'Guatemala City'), ('GUF', 'Cayenne'),
    ('GUM', 'Hagåtña'), ('GUY', 'Georgetown'), ('HKG', 'City of Victoria'),
    ('HND', 'Tegucigalpa'), ('HRV', 'Zagreb'), ('HTI', 'Port-au-Prince'),
    ('HUN', 'Budapest'), ('IDN', 'Jakarta'), ('IMN', 'Douglas'),
    ('IND', 'New Delhi'), ('IOT', 'Diego Garcia'), ('IRL', 'Dublin'),
    ('IRN', 'Tehran'), ('IRQ', 'Baghdad'), ('ISL', 'Reykjavik'),
    ('ISR', 'Jerusalem'), ('ITA', 'Rome'), ('JAM', 'Kingston'),
    ('JEY', 'Saint Helier'), ('JOR', 'Amman'), ('JPN', 'Tokyo'),
    ('KAZ', 'Astana'), ('KEN', 'Nairobi'), ('KGZ', 'Bishkek'),
    ('KHM', 'Phnom Penh'), ('KIR', 'South Tarawa'), ('KNA', 'Basseterre'),
    ('KOR', 'Seoul'), ('KWT', 'Kuwait City'), ('LAO', 'Vientiane'),
    ('LBN', 'Beirut'), ('LBR', 'Monrovia'), ('LBY', 'Tripoli'),
    ('LCA', 'Castries'), ('LIE', 'Vaduz'), ('LKA', 'Colombo'),
    ('LSO', 'Maseru'), ('LTU', 'Vilnius'), ('LUX', 'Luxembourg'),
    ('LVA', 'Riga'), ('MAF', 'Marigot'), ('MAR', 'Rabat'),
    ('MCO', 'Monaco'), ('MDA', 'Chișinău'), ('MDG', 'Antananarivo'),
    ('MDV', 'Malé'), ('MEX', 'Mexico City'), ('MHL', 'Majuro'),
    ('MKD', 'Skopje'), ('MLI', 'Bamako'), ('MLT', 'Valletta'),
    ('MMR', 'Naypyidaw'), ('MNE', 'Podgorica'), ('MNG', 'Ulan Bator'),
    ('MNP', 'Saipan'), ('MOZ', 'Maputo'), ('MRT', 'Nouakchott'),
    ('MSR', 'Plymouth'), ('MTQ', 'Fort-de-France'), ('MUS', 'Port Louis'),
    ('MWI', 'Lilongwe'), ('MYS', 'Kuala Lumpur'), ('MYT', 'Mamoudzou'),
    ('NAM', 'Windhoek'), ('NCL', 'Nouméa'), ('NER', 'Niamey'),
    ('NFK', 'Kingston'), ('NGA', 'Abuja'), ('NIC', 'Managua'),
    ('NIU', 'Alofi'), ('NLD', 'Amsterdam'), ('NOR', 'Oslo'),
    ('NPL', 'Kathmandu'), ('NRU', 'Yaren'), ('NZL', 'Wellington'),
    ('OMN', 'Muscat'), ('PAK', 'Islamabad'), ('PAN', 'Panama City'),
    ('PCN', 'Adamstown'), ('PER', 'Lima'), ('PHL', 'Manila'),
    ('PLW', 'Ngerulmud'), ('PNG', 'Port Moresby'), ('POL', 'Warsaw'),
    ('PRI', 'San Juan'), ('PRK', 'Pyongyang'), ('PRT', 'Lisbon'),
    ('PRY', 'Asunción'), ('PSE', 'Ramallah'), ('PYF', 'Papeetē'),
    ('QAT', 'Doha'), ('REU', 'Saint-Denis'), ('ROU', 'Bucharest'),
    ('RUS', 'Moscow'), ('RWA', 'Kigali'), ('SAU', 'Riyadh'),
    ('SDN', 'Khartoum'), ('SEN', 'Dakar'), ('SGP', 'Singapore'),
    ('SGS', 'King Edward Point'), ('SHN', 'Jamestown'), ('SJM', 'Longyearbyen'),
    ('SLB', 'Honiara'), ('SLE', 'Freetown'), ('SLV', 'San Salvador'),
    ('SMR', 'City of San Marino'), ('SOM', 'Mogadishu'), ('SPM', 'Saint-Pierre'),
    ('SRB', 'Belgrade'), ('SSD', 'Juba'), ('STP', 'São Tomé'),
    ('SUR', 'Paramaribo'), ('SVK', 'Bratislava'), ('SVN', 'Ljubljana'),
    ('SWE', 'Stockholm'), ('SWZ', 'Lobamba'), ('SXM', 'Philipsburg'),
    ('SYC', 'Victoria'), ('SYR', 'Damascus'), ('TCA', 'Cockburn Town'),
    ('TCD', 'N''Djamena'), ('TGO', 'Lomé'), ('THA', 'Bangkok'),
    ('TJK', 'Dushanbe'), ('TKL', 'Fakaofo'), ('TKM', 'Ashgabat'),
    ('TLS', 'Dili'), ('TON', 'Nuku''alofa'), ('TTO', 'Port of Spain'),
    ('TUN', 'Tunis'), ('TUR', 'Ankara'), ('TUV', 'Funafuti'),
    ('TWN', 'Taipei'), ('TZA', 'Dodoma'), ('UGA', 'Kampala'),
    ('UKR', 'Kyiv'), ('URY', 'Montevideo'), ('USA', 'Washington D.C.'),
    ('UZB', 'Tashkent'), ('VAT', 'Vatican City'), ('VCT', 'Kingstown'),
    ('VEN', 'Caracas'), ('VGB', 'Road Town'), ('VIR', 'Charlotte Amalie'),
    ('VNM', 'Hanoi'), ('VUT', 'Port Vila'), ('WLF', 'Mata-Utu'),
    ('WSM', 'Apia'), ('YEM', 'Sana''a'), ('ZAF', 'Bloemfontein'),
    ('ZAF', 'Cape Town'), ('ZAF', 'Pretoria'), ('ZMB', 'Lusaka'),
    ('ZWE', 'Harare')
) AS datos(iso, ciudad)
JOIN pais ON pais.k_codigo_iso = datos.iso
ON CONFLICT DO NOTHING;
